variable "default_subplan" {
  type        = string
  default     = null
  description = "(Optional) Resource type pricing default subplan. Contact your MSFT representative for possible values"
}

variable "default_tier" {
  type        = string
  default     = "Standard"
  description = "(Optional) The pricing tier to use. Possible values are `Free` and `Standard`"
  nullable    = false
}

variable "enable_telemetry" {
  type        = bool
  default     = true
  description = <<DESCRIPTION
This variable controls whether or not telemetry is enabled for the module.
For more information see https://aka.ms/avm/telemetryinfo.
If it is set to false, then no telemetry will be collected.
DESCRIPTION
  nullable    = false
}

variable "location" {
  type        = string
  default     = "uksouth"
  description = "(Optional) The location/region where the policy should exist."
}

variable "mdc_databases_plans" {
  type = set(string)
  default = [
    "OpenSourceRelationalDatabases",
    "SqlServers",
    "SqlServerVirtualMachines",
    "CosmosDbs",
  ]
  description = "(Optional) Set of all MDC databases plans"
  nullable    = false
}

variable "mdc_plans_list" {
  type = set(string)
  default = [
    "AppServices",
    "Arm",
    "CloudPosture",
    "Containers",
    "KeyVaults",
    "OpenSourceRelationalDatabases",
    "SqlServers",
    "SqlServerVirtualMachines",
    "CosmosDbs",
    "StorageAccounts",
    "VirtualMachines",
  ]
  description = "(Optional) Set of all MDC plans"
  nullable    = false

  validation {
    condition     = !contains(var.mdc_plans_list, "Api")
    error_message = "The 'Api' plan is deprecated and not supported by this module. Remove it from mdc_plans_list."
  }
}

variable "storage_accounts_malware_scan_cap_gb_per_month" {
  type        = string
  default     = "5000"
  description = "(Optional) Sets the maximum GB limit for malware scanning on uploaded files per storage account per month"
}

variable "subplans" {
  type        = map(string)
  default     = {}
  description = "(Optional) A map of resource type pricing subplan, the key is resource type. This variable takes precedence over `var.default_subplan`. Contact your MSFT representative for possible values"
  nullable    = false
}
variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = "Whether enable tracing tags that generated by BridgeCrew Yor."
  nullable    = false
}
variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = "Default prefix for generated tracing tags"
  nullable    = false
}

variable "create_policy_assignments" {
  type        = bool
  default     = true
  description = "Toggle to create policy assignment resources and their role assignments."
}

variable "subscription_id" {
  type        = string
  default     = null
  description = "(Optional) The subscription ID to target. If null, uses the current subscription context."
}
variable "ascExportResourceGroupLocation" {
  type        = string
  default     = "westeurope"
  description = "Location to create the export resource group"
}

variable "ascExportResourceGroupName" {
  type        = string
  default     = "rg-mdc-export"
  description = "Name for the export resource group"
}

variable "createResourceGroup" {
  type        = bool
  default     = true
  description = "If true, the module will create the export resource group specified by `ascExportResourceGroupName`"
}
variable "emailSecurityContact" {
  type        = string
  default     = ""
  description = "Email address for a security contact to use for notifications"
}

variable "minimalSeverity" {
  type        = string
  default     = "High"
  description = "Minimal severity level for notifications (Low|Medium|High|Critical)"
}

# Per-plan policy mode toggles. Use "DeployIfNotExists" to create assignments.
variable "enableAscForServers" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForServersVulnerabilityAssessments" {
  type    = string
  default = "DeployIfNotExists"
}

variable "vulnerabilityAssessmentProvider" {
  type    = string
  default = "mdeTvm"
}

variable "enableTvmCheck" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForAppServices" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForSql" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForOssDb" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForCosmosDbs" {
  type    = string
  default = "Disabled"
}

variable "enableAscForStorage" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForContainers" {
  type    = string
  default = "Disabled"
}

variable "enableAscForArm" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForCspm" {
  type    = string
  default = "DeployIfNotExists"
}

variable "enableAscForSqlOnVm" {
  type    = string
  default = "Disabled"
}

variable "enableAscForKeyVault" {
  type    = string
  default = "DeployIfNotExists"
}
variable "dcr_association_scope_id" {
  type        = string
  default     = null
  description = "Resource ID to associate the DCR to (subscription, resource group, VM/VMSS, etc.)."
}